import Head from 'next/head'
import Home1 from './../components/home'

import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <div>
          <Link rel="stylesheet" href="/login" style={{margin:'45%',color:'black',fontWeight:'bold'}}>login</Link>
          <br />
          <Link rel="stylesheet" href="/register" style={{margin:'45%',color:'black',fontWeight:'bold'}}>register</Link>
        </div>
      </main>
    </>
  )
}
